/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.heigvd.amt.gary.models;

/**
 *
 * @author Miguel
 */
public class App {
   private final String name;
   private final String description;
   private final String apiKey;
   private int nbUsers;
   
   public App(String name, String description, String apiKey, int nbUsers)
   {
      this.name = name;
      this.description = description;
      this.apiKey = apiKey;
      this.nbUsers = nbUsers;
   }
}

/**
 * FEEDBACK:
 * - think about getting rid of the header generated by the IDE. Either use your own
 *   header (you can configure Netbeans), or remove everything.
 * 
 * - for the first implementation, it's ok to define apiKey as a String. However, in the
 *   real model, apiKey should be a class. The reason is that an ApiKey has a state (enabled or disabled),
 *   that at some point you might want to associate a shared secret to the apiKey (for signaures), etc.
 * 
 * - this is a detail and personal preference, but isn't numberOfUsers more explicit than nbUsers? Always
 *   think about external developers / newcomers arriving in your code base.
 */